name: mitochime
channels: [conda-forge, bioconda, defaults]
dependencies:
  - python=3.11
  # Core bio tools
  - wgsim=1.13
  - minimap2=2.28
  - samtools=1.20
  - bwa=0.7.17
  - jellyfish=2.3.0
  - seqtk=1.4
  - fastqc=0.12.1
  - trimmomatic=0.39
  - getorganelle=1.7.7.0
  # Python libs
  - pip
  - numpy=1.26
  - pandas=2.2
  - scikit-learn=1.5
  - xgboost=2.0
  - matplotlib=3.9
  - seaborn=0.13
  - pyarrow=16.1
  - pyyaml=6.0
  - click=8.1
  - tqdm=4.66
  - biopython=1.83
  - pysam=0.22
  - networkx=3.3
  # Dev quality
  - black=24.8
  - isort=5.13
  - flake8=7.1
  - pre-commit=3.8
