name: mitochime
channels:
  - conda-forge
  - bioconda
channel_priority: strict
dependencies:
  - python=3.11
  - pip
  - ipykernel
  # ARM-safe bio tools
  - minimap2=2.28
  - wgsim = 1.13
  - samtools=1.20
  - seqtk=1.4
  - fastp=0.23.4
  - fastqc=0.12.1
  # Python libs
  - numpy=1.26
  - pandas=2.2
  - scikit-learn=1.5
  - xgboost=2.0
  - matplotlib=3.9
  - seaborn=0.13
  - pyarrow=16.1
  - pyyaml=6.0
  - click=8.1
  - tqdm=4.66
  - biopython=1.83
  - pysam=0.22
  - networkx=3.3
  # Dev / quality
  - black=24.8
  - isort=5.13
  - flake8=7.1
  - pre-commit=3.8
  - pytest
